name: Deploy Homelab Cluster
on:
  push:
    branches: [ gha-test ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Apply
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.TF_VAR_proxmox_api_url }}
          TF_VAR_proxmox_token_id: ${{ secrets.TF_VAR_proxmox_token_id }}
          TF_VAR_proxmox_token_secret: ${{ secrets.TF_VAR_proxmox_token_secret }}
          TF_VAR_ssh_key_path: ${{ secrets.TF_VAR_ssh_key_path }}
          TF_VAR_vm_configs: ${{ secrets.TF_VAR_vm_configs }}
        run: |
          cd terraform/k3s-cluster
          terraform init
          # github action test -> apply 미적용
          terraform plan

      - name: Wait for SSH
        run: sleep 30

      - name: Ansible Playbook
        run: |
          cd ansible
          ansible-playbook playbooks/bootstrap.yaml
          ansible-playbook playbooks/k3s.yaml