name: Deploy Homelab Cluster
on:
  push:
    branches: [ gha-test ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Apply
        run: |
          cd terraform/k3s-cluster
          terraform init
          terraform apply -auto-approve

      - name: Wait for SSH
        run: sleep 30

      - name: Ansible Playbook
        run: |
          cd ansible
          ansible-playbook playbooks/bootstrap.yaml
          ansible-playbook playbooks/k3s.yaml